
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int HERENCIA = 44;
  public static final int INC_DEC = 13;
  public static final int PAR_DER = 7;
  public static final int DATOS_DECIMALES = 32;
  public static final int OPERADORES_ARITMETICOS = 49;
  public static final int MODULARIDAD = 47;
  public static final int PATRONES_DE_DISENO = 52;
  public static final int CORCH_IZQ = 10;
  public static final int ARGUMENTO = 21;
  public static final int SI = 62;
  public static final int EXCEPCIONES = 41;
  public static final int DATOS_CARACTERES = 30;
  public static final int DATOS_ENTEROS = 33;
  public static final int BLOCKCHAIN = 23;
  public static final int DOS_PUNTOS = 5;
  public static final int HARDWARE = 43;
  public static final int MANEJO_DE_MEMORIA = 46;
  public static final int SERIALIZACION = 61;
  public static final int DATOS_BOOLEANOS = 29;
  public static final int CICLO = 24;
  public static final int REFERENCIA = 56;
  public static final int FIN = 16;
  public static final int PRECISION = 54;
  public static final int DATOS_COBOL = 31;
  public static final int LLAVE_IZQ = 8;
  public static final int DATOS_TEXTO = 35;
  public static final int IGUAL = 2;
  public static final int SINO = 63;
  public static final int DECLARAR = 37;
  public static final int CONCURRENCIA = 25;
  public static final int ARREGLOS = 22;
  public static final int NUM = 68;
  public static final int SALTAR = 14;
  public static final int ID = 67;
  public static final int RETORNO = 58;
  public static final int PUNTO_COMA = 3;
  public static final int CONJUNTOS = 26;
  public static final int OPERADORES_RELACIONALES = 51;
  public static final int EOF = 0;
  public static final int DATOS_NULOS = 34;
  public static final int SEGURIDAD = 60;
  public static final int COMILLAS = 12;
  public static final int error = 1;
  public static final int CORCH_DER = 11;
  public static final int COMA = 4;
  public static final int GENERICOS = 42;
  public static final int ENTRADA_Y_SALIDA = 39;
  public static final int DEBUG = 36;
  public static final int PAR_IZQ = 6;
  public static final int CONTEXTO = 27;
  public static final int REDES = 55;
  public static final int ALTO = 20;
  public static final int ERROR = 17;
  public static final int SWITCH = 64;
  public static final int CONTROL_FLOW = 28;
  public static final int ESTRUCTURAS = 40;
  public static final int OPERADOR = 48;
  public static final int LLAVE_DER = 9;
  public static final int PERSISTENCIA = 53;
  public static final int OPERADORES_LOGICOS = 50;
  public static final int INTERFACES_GRAFICAS = 45;
  public static final int ACCESO = 18;
  public static final int TIEMPO = 66;
  public static final int ALIAS = 19;
  public static final int INICIO = 15;
  public static final int REFLEXION = 57;
  public static final int DICCIONARIOS = 38;
  public static final int TESTING = 65;
  public static final int SALTO = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "PUNTO_COMA",
  "COMA",
  "DOS_PUNTOS",
  "PAR_IZQ",
  "PAR_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "CORCH_IZQ",
  "CORCH_DER",
  "COMILLAS",
  "INC_DEC",
  "SALTAR",
  "INICIO",
  "FIN",
  "ERROR",
  "ACCESO",
  "ALIAS",
  "ALTO",
  "ARGUMENTO",
  "ARREGLOS",
  "BLOCKCHAIN",
  "CICLO",
  "CONCURRENCIA",
  "CONJUNTOS",
  "CONTEXTO",
  "CONTROL_FLOW",
  "DATOS_BOOLEANOS",
  "DATOS_CARACTERES",
  "DATOS_COBOL",
  "DATOS_DECIMALES",
  "DATOS_ENTEROS",
  "DATOS_NULOS",
  "DATOS_TEXTO",
  "DEBUG",
  "DECLARAR",
  "DICCIONARIOS",
  "ENTRADA_Y_SALIDA",
  "ESTRUCTURAS",
  "EXCEPCIONES",
  "GENERICOS",
  "HARDWARE",
  "HERENCIA",
  "INTERFACES_GRAFICAS",
  "MANEJO_DE_MEMORIA",
  "MODULARIDAD",
  "OPERADOR",
  "OPERADORES_ARITMETICOS",
  "OPERADORES_LOGICOS",
  "OPERADORES_RELACIONALES",
  "PATRONES_DE_DISENO",
  "PERSISTENCIA",
  "PRECISION",
  "REDES",
  "REFERENCIA",
  "REFLEXION",
  "RETORNO",
  "SALTO",
  "SEGURIDAD",
  "SERIALIZACION",
  "SI",
  "SINO",
  "SWITCH",
  "TESTING",
  "TIEMPO",
  "ID",
  "NUM"
  };
}

